import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import localFont from 'next/font/local';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const phonkRegular = localFont({
  src: './fonts/Phonk/PhonkRegular.otf',  // Updated path
  variable: '--font-phonk-regular',
  display: 'swap',
});

const phonkContrast = localFont({
  src: './fonts/Phonk/PhonkContrast.otf',  // Updated path
  variable: '--font-phonk-contrast',
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`
      ${geistSans.variable} 
      ${geistMono.variable} 
      ${phonkRegular.variable} 
      ${phonkContrast.variable}
    `}>
      <body className="antialiased">
        <Navbar />
        {children}
      </body>
    </html>
  );
}